### ISSUE TITLE
PEAR.ControlStructures.MultilineConditionSpaceBeforeOpenBrace

### ISSUE THREAD

**Issue by pincher2012** [itmh/php-standard#6]
Срабатывает при `<?php if (Yii::$app->session->getFlash('gateway')): ?>`
Т. е. если нет пробела между закрывающей круглой скобкой if и ":"

**Comment by chshanovskiy** [comment]
Closed by a6ef7a4

**Comment by pincher2012** [comment]
Наверное не хватает точки после MultilineCondition, сорян.

**Comment by chshanovskiy** [comment]
Updated by 2c45623
